export const builtInCommands = [
    // AI and AI Agents
    { command: "open deepseek", url: "https://chat.deepseek.com/swde" },
    { command: "open chatgpt", url: "https://chat.openai.com" },
    { command: "open bard", url: "https://bard.google.com" },
    { command: "open claude", url: "https://claude.ai" },
    { command: "open perplexity", url: "https://www.perplexity.ai" },
    { command: "open huggingface", url: "https://huggingface.co" },
    { command: "open midjourney", url: "https://www.midjourney.com" },
    { command: "open dalle", url: "https://labs.openai.com" },
    { command: "open stable diffusion", url: "https://stability.ai" },
    { command: "open openai", url: "https://openai.com" },
    { command: "open deepmind", url: "https://deepmind.com" },
    { command: "open replicate", url: "https://replicate.com" },
    { command: "open langchain", url: "https://www.langchain.com" },
    { command: "open cohere", url: "https://cohere.ai" },
    { command: "open anthropic", url: "https://www.anthropic.com" },
    { command: "open runwayml", url: "https://runwayml.com" },
    { command: "open elevenlabs", url: "https://elevenlabs.io" },
    { command: "open assemblyai", url: "https://www.assemblyai.com" },
    { command: "open opencv", url: "https://opencv.org" },
    { command: "open tensorflow", url: "https://www.tensorflow.org" },
    { command: "open pytorch", url: "https://pytorch.org" },
    { command: "open keras", url: "https://keras.io" },
    { command: "open fastai", url: "https://www.fast.ai" },
    { command: "open huggingface spaces", url: "https://huggingface.co/spaces" },
    { command: "open gradio", url: "https://www.gradio.app" },
    { command: "open streamlit", url: "https://streamlit.io" },
    { command: "open weights and biases", url: "https://wandb.ai" },
    { command: "open comet ml", url: "https://www.comet.ml" },
    { command: "open papers with code", url: "https://paperswithcode.com" },
    { command: "open arxiv", url: "https://arxiv.org" },
    { command: "open openai playground", url: "https://platform.openai.com/playground" },
    { command: "open google ai", url: "https://ai.google" },
    { command: "open meta ai", url: "https://ai.facebook.com" },
    { command: "open nvidia ai", url: "https://www.nvidia.com/en-us/ai-data-science/" },
    { command: "open huggingface datasets", url: "https://huggingface.co/datasets" },
    { command: "open kaggle", url: "https://www.kaggle.com" },
    { command: "open colab", url: "https://colab.research.google.com" },
    { command: "open deepai", url: "https://deepai.org" },
    { command: "open bigml", url: "https://bigml.com" },
    { command: "open dialogflow", url: "https://dialogflow.cloud.google.com" },
    { command: "open rasa", url: "https://rasa.com" },
    { command: "open wit.ai", url: "https://wit.ai" },
    { command: "open mlflow", url: "https://mlflow.org" },
    { command: "open sagemaker", url: "https://aws.amazon.com/sagemaker/" },
    { command: "open vertex ai", url: "https://cloud.google.com/vertex-ai" },
    { command: "open azure machine learning", url: "https://azure.microsoft.com/en-us/services/machine-learning/" },
  
    // Tech and Development
    { command: "open github", url: "https://github.com" },
    { command: "open gitlab", url: "https://gitlab.com" },
    { command: "open bitbucket", url: "https://bitbucket.org" },
    { command: "open stack overflow", url: "https://stackoverflow.com" },
    { command: "open dev.to", url: "https://dev.to" },
    { command: "open hashnode", url: "https://hashnode.com" },
    { command: "open medium", url: "https://medium.com" },
    { command: "open freecodecamp", url: "https://www.freecodecamp.org" },
    { command: "open codepen", url: "https://codepen.io" },
    { command: "open jsfiddle", url: "https://jsfiddle.net" },
    { command: "open replit", url: "https://replit.com" },
    { command: "open glitch", url: "https://glitch.com" },
    { command: "open docker", url: "https://www.docker.com" },
    { command: "open kubernetes", url: "https://kubernetes.io" },
    { command: "open aws", url: "https://aws.amazon.com" },
    { command: "open google cloud", url: "https://cloud.google.com" },
    { command: "open azure", url: "https://azure.microsoft.com" },
    { command: "open vercel", url: "https://vercel.com" },
    { command: "open netlify", url: "https://www.netlify.com" },
    { command: "open heroku", url: "https://www.heroku.com" },
    { command: "open digitalocean", url: "https://www.digitalocean.com" },
    { command: "open linode", url: "https://www.linode.com" },
    { command: "open cloudflare", url: "https://www.cloudflare.com" },
    { command: "open npm", url: "https://www.npmjs.com" },
    { command: "open yarn", url: "https://yarnpkg.com" },
    { command: "open pypi", url: "https://pypi.org" },
    { command: "open crates.io", url: "https://crates.io" },
    { command: "open rubygems", url: "https://rubygems.org" },
    { command: "open maven", url: "https://mvnrepository.com" },
    { command: "open nuget", url: "https://www.nuget.org" },
    { command: "open postman", url: "https://www.postman.com" },
    { command: "open insomnia", url: "https://insomnia.rest" },
    { command: "open swagger", url: "https://swagger.io" },
    { command: "open graphql", url: "https://graphql.org" },
    { command: "open apache kafka", url: "https://kafka.apache.org" },
    { command: "open rabbitmq", url: "https://www.rabbitmq.com" },
    { command: "open redis", url: "https://redis.io" },
    { command: "open mongodb", url: "https://www.mongodb.com" },
    { command: "open mysql", url: "https://www.mysql.com" },
    { command: "open postgresql", url: "https://www.postgresql.org" },
    { command: "open sqlite", url: "https://www.sqlite.org" },
    { command: "open elasticsearch", url: "https://www.elastic.co" },
    { command: "open kibana", url: "https://www.elastic.co/kibana" },
    { command: "open logstash", url: "https://www.elastic.co/logstash" },
    { command: "open prometheus", url: "https://prometheus.io" },
    { command: "open grafana", url: "https://grafana.com" },
    { command: "open jenkins", url: "https://www.jenkins.io" },
    { command: "open circleci", url: "https://circleci.com" },
    { command: "open travis ci", url: "https://travis-ci.org" },
    { command: "open github actions", url: "https://github.com/features/actions" },
    { command: "open gitlab ci", url: "https://docs.gitlab.com/ee/ci/" },
    { command: "open terraform", url: "https://www.terraform.io" },
    { command: "open ansible", url: "https://www.ansible.com" },
    { command: "open puppet", url: "https://puppet.com" },
    { command: "open chef", url: "https://www.chef.io" },
    { command: "open istio", url: "https://istio.io" },
    { command: "open envoy", url: "https://www.envoyproxy.io" },
    { command: "open grpc", url: "https://grpc.io" },
    { command: "open protobuf", url: "https://developers.google.com/protocol-buffers" },
    { command: "open openapi", url: "https://www.openapis.org" },
    { command: "open kubernetes dashboard", url: "https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/" },
  
    // E-commerce
    { command: "open flipkart", url: "https://www.flipkart.com" },
    { command: "open amazon india", url: "https://www.amazon.in" },
    { command: "open myntra", url: "https://www.myntra.com" },
    { command: "open nykaa", url: "https://www.nykaa.com" },
    { command: "open meesho", url: "https://www.meesho.com" },
    { command: "open snapdeal", url: "https://www.snapdeal.com" },
    { command: "open ajio", url: "https://www.ajio.com" },
    { command: "open firstcry", url: "https://www.firstcry.com" },
    { command: "open tatacliq", url: "https://www.tatacliq.com" },
    { command: "open shopclues", url: "https://www.shopclues.com" },
    { command: "open paytm mall", url: "https://paytmmall.com" },
    { command: "open limeroad", url: "https://www.limeroad.com" },
    { command: "open 1mg", url: "https://www.1mg.com" },
    { command: "open pharmeasy", url: "https://www.pharmeasy.in" },
    { command: "open netmeds", url: "https://www.netmeds.com" },
  
    // Productivity and Tools
    { command: "open notion", url: "https://www.notion.so" },
    { command: "open figma", url: "https://www.figma.com" },
    { command: "open canva", url: "https://www.canva.com" },
    { command: "open slack", url: "https://slack.com" },
    { command: "open trello", url: "https://trello.com" },
    { command: "open asana", url: "https://asana.com" },
    { command: "open zoom", url: "https://zoom.us" },
    { command: "open microsoft teams", url: "https://teams.microsoft.com" },
    { command: "open google docs", url: "https://docs.google.com" },
    { command: "open google sheets", url: "https://sheets.google.com" },
    { command: "open google slides", url: "https://slides.google.com" },
    { command: "open google drive", url: "https://drive.google.com" },
    { command: "open dropbox", url: "https://www.dropbox.com" },
    { command: "open onedrive", url: "https://onedrive.live.com" },
  
    // Learning and Coding Platforms
    { command: "open coursera", url: "https://www.coursera.org" },
    { command: "open udemy", url: "https://www.udemy.com" },
    { command: "open khan academy", url: "https://www.khanacademy.org" },
    { command: "open edx", url: "https://www.edx.org" },
    { command: "open codecademy", url: "https://www.codecademy.com" },
    { command: "open leetcode", url: "https://leetcode.com" },
    { command: "open hackerrank", url: "https://www.hackerrank.com" },
    { command: "open codewars", url: "https://www.codewars.com" },
    { command: "open codechef", url: "https://www.codechef.com" },
    { command: "open exercism", url: "https://exercism.org" },
    { command: "open topcoder", url: "https://www.topcoder.com" },
    { command: "open codility", url: "https://www.codility.com" },
    { command: "open geeksforgeeks", url: "https://www.geeksforgeeks.org" },
    { command: "open w3schools", url: "https://www.w3schools.com" },
    { command: "open freecodecamp", url: "https://www.freecodecamp.org" },
    { command: "open pluralsight", url: "https://www.pluralsight.com" },
    { command: "open linkedin learning", url: "https://www.linkedin.com/learning/" },
    { command: "open skillshare", url: "https://www.skillshare.com" },
    { command: "open datacamp", url: "https://www.datacamp.com" },
    { command: "open udacity", url: "https://www.udacity.com" },
    { command: "open futurelearn", url: "https://www.futurelearn.com" },
    { command: "open alison", url: "https://alison.com" },
    { command: "open openclassrooms", url: "https://openclassrooms.com" },
    { command: "open mit opencourseware", url: "https://ocw.mit.edu" },
    { command: "open stanford online", url: "https://online.stanford.edu" },
    { command: "open harvard online learning", url: "https://online-learning.harvard.edu" },
    { command: "open google developers", url: "https://developers.google.com" },
    { command: "open microsoft learn", url: "https://learn.microsoft.com" },
    { command: "open aws training", url: "https://aws.amazon.com/training/" },
    { command: "open google cloud training", url: "https://cloud.google.com/training" },
    { command: "open ibm skillsbuild", url: "https://skillsbuild.org" },
    { command: "open oracle university", url: "https://education.oracle.com" },
    { command: "open red hat training", url: "https://www.redhat.com/en/services/training" },
    { command: "open cisco networking academy", url: "https://www.netacad.com" },
    { command: "open comptia", url: "https://www.comptia.org" },
    { command: "open linux foundation training", url: "https://training.linuxfoundation.org" },
    { command: "open raspberry pi foundation", url: "https://www.raspberrypi.org" },
    { command: "open arduino", url: "https://www.arduino.cc" },
    { command: "open adafruit", url: "https://www.adafruit.com" },
    { command: "open sparkfun", url: "https://www.sparkfun.com" },
    { command: "open element14", url: "https://www.element14.com" },
    { command: "open hackster.io", url: "https://www.hackster.io" },
    { command: "open instructables", url: "https://www.instructables.com" },
    { command: "open maker pro", url: "https://maker.pro" },
    { command: "open hackaday", url: "https://hackaday.com" },
    { command: "open hack the box", url: "https://www.hackthebox.com" },
    { command: "open tryhackme", url: "https://tryhackme.com" },
    { command: "open overthewire", url: "https://overthewire.org" },
    { command: "open picoctf", url: "https://picoctf.org" },
    { command: "open ctftime", url: "https://ctftime.org" },
    { command: "open vulnhub", url: "https://www.vulnhub.com" },
    { command: "open security onion", url: "https://securityonion.net" },
    { command: "open kali linux", url: "https://www.kali.org" },
    { command: "open parrot os", url: "https://www.parrotsec.org" },
    { command: "open blackarch", url: "https://blackarch.org" },
    { command: "open offensive security", url: "https://www.offensive-security.com" },
    { command: "open sans institute", url: "https://www.sans.org" },
    { command: "open cisa", url: "https://www.cisa.gov" },
    { command: "open nist", url: "https://www.nist.gov" },
    { command: "open owasp", url: "https://owasp.org" },
    { command: "open mitre att&ck", url: "https://attack.mitre.org" },
    { command: "open cve details", url: "https://www.cvedetails.com" },
    { command: "open exploit-db", url: "https://www.exploit-db.com" },
    { command: "open packet storm security", url: "https://packetstormsecurity.com" },
    { command: "open security focus", url: "https://www.securityfocus.com" },
    { command: "open securitytrails", url: "https://securitytrails.com" },
    { command: "open shodan", url: "https://www.shodan.io" },
    { command: "open censys", url: "https://censys.io" },
    { command: "open zoomeye", url: "https://www.zoomeye.org" },
    { command: "open binary edge", url: "https://www.binaryedge.io" },
    { command: "open grey noise", url: "https://www.greynoise.io" },
    { command: "open hunter.io", url: "https://hunter.io" },
    { command: "open have i been pwned", url: "https://haveibeenpwned.com" },
    { command: "open dehashed", url: "https://www.dehashed.com" },
    { command: "open breach alarm", url: "https://breachalarm.com" },
    { command: "open snort", url: "https://www.snort.org" },
    { command: "open suricata", url: "https://suricata.io" },
    { command: "open zeek", url: "https://www.zeek.org" },
    { command: "open osquery", url: "https://osquery.io" },
    { command: "open sysdig", url: "https://sysdig.com" },
    { command: "open falco", url: "https://falco.org" },
    { command: "open ossec", url: "https://www.ossec.net" },
    { command: "open wazuh", url: "https://wazuh.com" },
    { command: "open elk stack", url: "https://www.elastic.co/what-is/elk-stack" },
    { command: "open splunk", url: "https://www.splunk.com" },
    { command: "open graylog", url: "https://www.graylog.org" },
    { command: "open logrhythm", url: "https://logrhythm.com" },
    { command: "open qradar", url: "https://www.ibm.com/security/security-intelligence/qradar" },
  
    // Social Media and News
    { command: "open google", url: "https://google.com" },
    { command: "open youtube", url: "https://www.youtube.com" },
    { command: "open twitter", url: "https://twitter.com" },
    { command: "open facebook", url: "https://www.facebook.com" },
    { command: "open instagram", url: "https://www.instagram.com" },
    { command: "open linkedin", url: "https://www.linkedin.com" },
    { command: "open reddit", url: "https://www.reddit.com" },
    { command: "open tiktok", url: "https://www.tiktok.com" },
    { command: "open pinterest", url: "https://www.pinterest.com" },
    { command: "open nytimes", url: "https://www.nytimes.com" },
    { command: "open bbc", url: "https://www.bbc.com" },
    { command: "open cnn", url: "https://www.cnn.com" },
    { command: "open techcrunch", url: "https://techcrunch.com" },
    { command: "open the verge", url: "https://www.theverge.com" },
    { command: "open wired", url: "https://www.wired.com" },
  
    // Entertainment
    { command: "open netflix", url: "https://www.netflix.com" },
    { command: "open youtube", url: "https://www.youtube.com" },
    { command: "open spotify", url: "https://www.spotify.com" },
    { command: "open disney plus", url: "https://www.disneyplus.com" },
    { command: "open amazon prime video", url: "https://www.primevideo.com" },
    { command: "open apple tv", url: "https://tv.apple.com" },
    { command: "open twitch", url: "https://www.twitch.tv" },
    { command: "open crunchyroll", url: "https://www.crunchyroll.com" },
    { command: "open imdb", url: "https://www.imdb.com" },
    { command: "open rotten tomatoes", url: "https://www.rottentomatoes.com" },
    { command: "open goodreads", url: "https://www.goodreads.com" },
    { command: "open audible", url: "https://www.audible.com" },
    { command: "open kindle", url: "https://www.amazon.com/kindle" },
    { command: "open steam", url: "https://store.steampowered.com" },
    { command: "open epic games", url: "https://www.epicgames.com" },
    { command: "open xbox", url: "https://www.xbox.com" },
    { command: "open playstation", url: "https://www.playstation.com" },
    { command: "open nintendo", url: "https://www.nintendo.com" },
    { command: "open tiktok", url: "https://www.tiktok.com" },
    { command: "open instagram", url: "https://www.instagram.com" },
    { command: "open pinterest", url: "https://www.pinterest.com" },
    // Entertainment (India Focused)
    { command: "open hotstar", url: "https://www.hotstar.com" },
    { command: "open sonyliv", url: "https://www.sonyliv.com" },
    { command: "open zee5", url: "https://www.zee5.com" },
    { command: "open voot", url: "https://www.voot.com" },
    { command: "open mx player", url: "https://www.mxplayer.in" },
    { command: "open jio cinema", url: "https://www.jiocinema.com" },
    { command: "open alt balaji", url: "https://www.altbalaji.com" },
    { command: "open eros now", url: "https://www.erosnow.com" },
    { command: "open hungama", url: "https://www.hungama.com" },
    { command: "open gaana", url: "https://gaana.com" },
    { command: "open wynk music", url: "https://wynk.in/music" },
    { command: "open jio saavn", url: "https://www.jiosaavn.com" },
    { command: "open spotify india", url: "https://www.spotify.com/in" },
    { command: "open bookmyshow", url: "https://www.bookmyshow.com" },
    { command: "open inox movies", url: "https://www.inoxmovies.com" },
    { command: "open pvr cinemas", url: "https://www.pvrcinemas.com" },
    { command: "open netflix india", url: "https://www.netflix.com/in" },
    { command: "open amazon prime india", url: "https://www.primevideo.com" },
    { command: "open youtube india", url: "https://www.youtube.com" },
  
    // Job and Career
    { command: "open naukri", url: "https://www.naukri.com" },
    { command: "open shine", url: "https://www.shine.com" },
    { command: "open monster india", url: "https://www.monsterindia.com" },
    { command: "open times jobs", url: "https://www.timesjobs.com" },
    { command: "open linkedin jobs india", url: "https://www.linkedin.com/jobs" },
    { command: "open indeed india", url: "https://www.indeed.co.in" },
    { command: "open freshersworld", url: "https://www.freshersworld.com" },
    { command: "open placement india", url: "https://www.placementindia.com" },
    { command: "open foundit", url: "https://www.foundit.in" },
    { command: "open apna", url: "https://www.apna.co" },
    { command: "open hirist", url: "https://www.hirist.com" },
    { command: "open angel list india", url: "https://angel.co/india" },
    { command: "open upwork india", url: "https://www.upwork.com" },
    { command: "open fiverr india", url: "https://www.fiverr.com" },
    { command: "open freelancer india", url: "https://www.freelancer.in" },
    { command: "open workindia", url: "https://www.workindia.in" },
    { command: "open quikr jobs", url: "https://www.quikr.com/jobs" },
    { command: "open babajob", url: "https://www.babajob.com" },
    { command: "open grabjobs india", url: "https://www.grabjobs.co/india" },
    { command: "open wisdom jobs", url: "https://www.wisdomjobs.com" },
    { command: "open sarkari result", url: "https://www.sarkariresult.com" },
    { command: "open sarkari naukri", url: "https://www.sarkarinaukri.com" },
    { command: "open freejobalert", url: "https://www.freejobalert.com" },
    { command: "open government jobs", url: "https://www.governmentjobs.com" },
    { command: "open indian government jobs", url: "https://www.indgovtjobs.in" },
    { command: "open indian army recruitment", url: "https://www.joinindianarmy.nic.in" },
    { command: "open indian navy recruitment", url: "https://www.joinindiannavy.gov.in" },
    { command: "open indian air force recruitment", url: "https://careerindianairforce.cdac.in" },
    { command: "open upsc", url: "https://www.upsc.gov.in" },
    { command: "open ssc", url: "https://ssc.nic.in" },
    { command: "open ibps", url: "https://www.ibps.in" },
    { command: "open rrb", url: "https://www.rrbcdg.gov.in" },
    { command: "open state govt jobs", url: "https://www.indgovtjobs.in/state-government-jobs" },
    { command: "open teaching jobs india", url: "https://www.schooleduinfo.com" },
    { command: "open teaching jobs", url: "https://www.teachingjobs.co.in" },
    { command: "open private teacher jobs", url: "https://www.teacheron.com" },
    { command: "open it jobs india", url: "https://www.itjobs.in" },
    { command: "open startup jobs india", url: "https://www.angel.co/india/jobs" },
    { command: "open remote jobs india", url: "https://www.remote.co/remote-jobs/india" },
    { command: "open internshala", url: "https://www.internshala.com" },
    { command: "open letsintern", url: "https://www.letsintern.com" },
    { command: "open chegg internships", url: "https://www.internships.com" },
    { command: "open youth4work", url: "https://www.youth4work.com" },
    { command: "open talentrack", url: "https://www.talentrack.in" },
    { command: "open gig india", url: "https://www.gigindia.in" },
    { command: "open gig workers", url: "https://www.gigworker.in" },
    { command: "open gig economy india", url: "https://www.gigeconomy.in" },
    { command: "open gig jobs india", url: "https://www.gigjobs.in" },
    { command: "open gig workers india", url: "https://www.gigworkers.in" },
    { command: "open gig economy jobs", url: "https://www.gigeconomyjobs.in" },
    { command: "open gig jobs", url: "https://www.gigjobs.in" },
    { command: "open gig workers", url: "https://www.gigworker.in" },
    { command: "open gig economy india", url: "https://www.gigeconomy.in" },
    { command: "open gig jobs india", url: "https://www.gigjobs.in" },
    { command: "open gig workers india", url: "https://www.gigworkers.in" },
    { command: "open gig economy jobs", url: "https://www.gigeconomyjobs.in" },
    // Travel (India Focused)
    { command: "open makemytrip", url: "https://www.makemytrip.com" },
    { command: "open goibibo", url: "https://www.goibibo.com" },
    { command: "open cleartrip", url: "https://www.cleartrip.com" },
    { command: "open yatra", url: "https://www.yatra.com" },
    { command: "open ixigo", url: "https://www.ixigo.com" },
    { command: "open easemytrip", url: "https://www.easemytrip.com" },
    { command: "open redbus", url: "https://www.redbus.in" },
    { command: "open irctc", url: "https://www.irctc.co.in" },
    { command: "open oyo", url: "https://www.oyorooms.com" },
    { command: "open treebo", url: "https://www.treebo.com" },
    { command: "open fabhotels", url: "https://www.fabhotels.com" },
    { command: "open mmt holidays", url: "https://www.makemytrip.com/holidays-india" },
    { command: "open thomascook india", url: "https://www.thomascook.in" },
    { command: "open savaari", url: "https://www.savaari.com" },
    { command: "open zoomcar", url: "https://www.zoomcar.com" },
    { command: "open revv", url: "https://www.revv.co.in" },
    { command: "open thrillophilia", url: "https://www.thrillophilia.com" },
    // Food and Dining (India Focused)
    { command: "open swiggy", url: "https://www.swiggy.com" },
    { command: "open zomato", url: "https://www.zomato.com" },
    { command: "open dunzo", url: "https://www.dunzo.com" },
    { command: "open bigbasket", url: "https://www.bigbasket.com" },
    { command: "open blinkit", url: "https://www.blinkit.com" },
    { command: "open zepto", url: "https://www.zepto.com" },
    { command: "open dominos india", url: "https://www.dominos.co.in" },
    { command: "open pizzahut india", url: "https://www.pizzahut.co.in" },
    { command: "open uber eats india", url: "https://www.ubereats.com/in" },
    { command: "open eatfit", url: "https://www.eatfit.com" },
    { command: "open faasos", url: "https://www.faasos.com" },
  
    // Fitness and Health
    { command: "open paytm", url: "https://www.paytm.com" },
    { command: "open phonepe", url: "https://www.phonepe.com" },
    { command: "open google pay india", url: "https://pay.google.com" },
    { command: "open bhim upi", url: "https://www.bhimupi.org.in" },
    { command: "open cred", url: "https://www.cred.club" },
    { command: "open groww", url: "https://www.groww.in" },
    { command: "open zerodha", url: "https://www.zerodha.com" },
    { command: "open upstox", url: "https://www.upstox.com" },
    { command: "open policybazaar", url: "https://www.policybazaar.com" },
    { command: "open paisabazaar", url: "https://www.paisabazaar.com" },
    { command: "open bankbazaar", url: "https://www.bankbazaar.com" },
    { command: "open moneycontrol", url: "https://www.moneycontrol.com" },
    { command: "open et money", url: "https://www.etmoney.com" },
    { command: "open smallcase", url: "https://www.smallcase.com" },
    { command: "open kuvera", url: "https://www.kuvera.in" },
    { command: "open cult.fit", url: "https://www.cult.fit" },
    { command: "open healthify me", url: "https://www.healthifyme.com" },
    { command: "open fitternity", url: "https://www.fitternity.com" },
    { command: "open cure.fit", url: "https://www.cure.fit" },
    { command: "open practo", url: "https://www.practo.com" },
    { command: "open 1mg", url: "https://www.1mg.com" },
    { command: "open pharmeasy", url: "https://www.pharmeasy.in" },
    { command: "open netmeds", url: "https://www.netmeds.com" },
    { command: "open apollo 24/7", url: "https://www.apollopharmacy.in" },
    { command: "open lybrate", url: "https://www.lybrate.com" },
    { command: "open mfine", url: "https://www.mfine.co" },
    { command: "open thriwe", url: "https://www.thriwe.com" },
    { command: "open urban company", url: "https://www.urbancompany.com" },
    { command: "open housejoy", url: "https://www.housejoy.in" },
    { command: "open justdial", url: "https://www.justdial.com" },
    { command: "open practo", url: "https://www.practo.com" },
    { command: "open dunzo", url: "https://www.dunzo.com" },
    { command: "open porter", url: "https://www.porter.in" },
    { command: "open lic india", url: "https://www.licindia.in" },
    { command: "open irctc tourism", url: "https://www.irctctourism.com" },
  
    // News and Magazines
    { command: "open times of india", url: "https://timesofindia.indiatimes.com" },
    { command: "open the hindu", url: "https://www.thehindu.com" },
    { command: "open ndtv", url: "https://www.ndtv.com" },
    { command: "open indian express", url: "https://indianexpress.com" },
    { command: "open hindustan times", url: "https://www.hindustantimes.com" },
    { command: "open news18", url: "https://www.news18.com" },
    { command: "open republic world", url: "https://www.republicworld.com" },
    { command: "open india today", url: "https://www.indiatoday.in" },
    { command: "open live mint", url: "https://www.livemint.com" },
    { command: "open economic times", url: "https://economictimes.indiatimes.com" },
    { command: "open business standard", url: "https://www.business-standard.com" },
  
    // real estate
    { command: "open magicbricks", url: "https://www.magicbricks.com" },
    { command: "open 99acres", url: "https://www.99acres.com" },
    { command: "open housing.com", url: "https://www.housing.com" },
    { command: "open nobroker", url: "https://www.nobroker.in" },
    { command: "open commonfloor", url: "https://www.commonfloor.com" },
    { command: "open makaan.com", url: "https://www.makaan.com" },
    { command: "open proptiger", url: "https://www.proptiger.com" },
  
    // gaming
    { command: "open dream11", url: "https://www.dream11.com" },
    { command: "open myteam11", url: "https://www.myteam11.com" },
    { command: "open mpl", url: "https://www.mpl.live" },
    { command: "open winzo", url: "https://www.winzo.in" },
    { command: "open rummycircle", url: "https://www.rummycircle.com" },
    { command: "open pokerbaazi", url: "https://www.pokerbaazi.com" },
  
  ];